<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNo2ZcA3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNo2ZcA3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNo2ZcA3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNo2ZcA3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNo2ZcA3\App_KernelDevDebugContainer([
    'container.build_hash' => 'No2ZcA3',
    'container.build_id' => 'c84ec8c5',
    'container.build_time' => 1616797120,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNo2ZcA3');
