<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQaxF1Yx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQaxF1Yx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQaxF1Yx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQaxF1Yx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQaxF1Yx\App_KernelDevDebugContainer([
    'container.build_hash' => 'QaxF1Yx',
    'container.build_id' => '59fcd241',
    'container.build_time' => 1616794890,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQaxF1Yx');
